### ISSUE TITLE
Upgrade aimmdb to new tiled

### ISSUE THREAD

**Issue by dylanmcreynolds** [AI-multimodal/aimmdb#64]
AIMMDB is based on a pretty old version of tiled, where everything was based on and stored in Mongo. Tiled has progressed to use sqllite or postgres. We need to upgrade the aimmdb to a more modern version of tiled, which should be a single effort that also lets us remove much of the custom code that was built along the way into the aimmdb.

Some functionality will be lost, at the expense of much better maintainabilty:

- This will no longer support the kay/value browsing functionality.
- We would lose, I think, the data validation logic? Can this easily be preserved?

I think the work looks something like:

- [ ] Change spin from using the docker image from this repo to using the standard tiled image
- [ ] Change configuration yaml, adding snippet below
- [ ] Reload data from the client

example config.yaml addition:
``` yaml
trees:
  - path: /
    tree: catalog
    args:
      uri: /data/aimm/catalog.db # change to postgres
      writable_storage: /data/aimm/data
    access_control:
      access_policy: tiled.access_policies:SimpleAccessPolicy
      args:
        provider: orcid
        access_lists:
          <an orcid> : tiled.access_policies:ALL_ACCESS 
          <another orcid> : tiled.access_policies:ALL_ACCESS 
```
